version: '3'

services:
  app:
    build:
      context: .cloud/docker
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8.1.6
    image: laravel-app
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application:cached
      
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel-blog
    volumes:
      - db-data:/var/lib/mysql:cached

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db-data:












#version: '3'
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        - PHP_VERSION=8.1.6
#    ports:
#      - 8080:80
#    volumes:
#      - .:/var/www/html
#    depends_on:
#      - database
#  database:
#    image: mysql:5.7
#    environment:
#      MYSQL_DATABASE: laravel
#      MYSQL_ROOT_PASSWORD: secret
#    volumes:
#      - dbdata:/var/lib/mysql
#volumes:
#  dbdata:
